### ISSUE TITLE
Dump to TOML

### ISSUE THREAD

**Issue by noraj** [syeopite/ctoml-cr#1]
It seems there is a parse feature (TOML -> object) but no dump feature (object -> TOML).

**Comment by syeopite** [comment]
Sorry about the late reply.

I think a dumps feature is probably out of scope for this shard, as its merely a simple binding to tomlc99 and the upstream library does not support toml serialization, only parsing. See https://github.com/cktan/tomlc99/issues/91

**Comment by noraj** [comment]
I agree. As it's a binding if upstream doesn't support it, it's out of scope.
